[package]
name="029_bipmatch"
authors=["David J. Pearce"]

[build]
platforms=["whiley","boogie"]

[build.whiley]
source="/"

[check]
min=-1
max=4
length=4
depth=1
ignores=["main"]

[dependencies]
wybenchparser="1.0.0"

