[package]
name="008_scc"
authors=["David J. Pearce"]

[build]
platforms=["whiley"]

[build.whiley]
source="/"

[check]
min=-1
max=0
length=1
depth=1

[dependencies]
wybenchparser="1.0.0"
std="0.2.11"
