[package]
name="018_heap"
authors=["David J. Pearce"]

[build]
platforms=["whiley","boogie"]

[build.whiley]
source="/"

[build.boogie]
timeout=120

[check]
min=-1
max=2
length=4
depth=1

[dependencies]
std="0.3.1"

