[package]
name="033_bank"
authors=["David J. Pearce"]

[build]
platforms=["whiley","boogie2"]

[build.whiley]
source="/"

[check]
min=-1
max=1
length=2
depth=1
ignores=["main"]

[dependencies]
wybenchparser="1.0.0"

