[package]
name="004_matrix"
authors=["David J. Pearce"]

[build]
platforms=["whiley","boogie2"]

[build.whiley]
source="/"

[check]
min=-1
max=1
length=4
depth=2
ignores=["main"]

[dependencies]
wybenchparser="1.0.0"
