[package]
name="004_matrix"
authors=["David J. Pearce"]

[build]
platforms=["whiley"]

[build.whiley]
source="/"

[check]
min=-1
max=2
length=2
depth=1

[dependencies]
wybenchparser="1.0.0"
std="0.2.11"
